# Site settings
# site title
title: Ranger
# ur email
email: Ranger@xianyu.io
# a intro for the site
description: front-end dev.
# site base url
baseurl: ""
# site address @ internet
url: "http://blog.xianyu.io"
# github username
github_username:  RangerChen
# vbo username
weibo_username:  Rangerccx
# Build settings
markdown: kramdown
# timezone setting
timezone: Asia/Shanghai